// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOnNlygw12T8YDxrwuSEbXLZodNZGztpU',
    appId: '1:361266947064:web:9b2fe309a87f4ec24dec0d',
    messagingSenderId: '361266947064',
    projectId: 'financial-tracker-4791d',
    authDomain: 'financial-tracker-4791d.firebaseapp.com',
    storageBucket: 'financial-tracker-4791d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcwR04VBmHFdB0NVkYUUUOzt38NabOdzo',
    appId: '1:361266947064:android:02c32583510662114dec0d',
    messagingSenderId: '361266947064',
    projectId: 'financial-tracker-4791d',
    storageBucket: 'financial-tracker-4791d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANq6iNMUz3CVW4QQgTUA84h0C5wU_yy5o',
    appId: '1:361266947064:ios:260e4b383f9a9f7c4dec0d',
    messagingSenderId: '361266947064',
    projectId: 'financial-tracker-4791d',
    storageBucket: 'financial-tracker-4791d.firebasestorage.app',
    iosClientId:
        '361266947064-8torhm8lco4ok9770rvmm48vpkjfppll.apps.googleusercontent.com',
    iosBundleId: 'com.irfanmaulanaakbar.financialTracker',
  );
}
